// Code generated by protoc-gen-go. DO NOT EDIT.
// source: remoteExec.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CmdResult struct {
	Result               string   `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdResult) Reset()         { *m = CmdResult{} }
func (m *CmdResult) String() string { return proto.CompactTextString(m) }
func (*CmdResult) ProtoMessage()    {}
func (*CmdResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_8429525101601a29, []int{0}
}

func (m *CmdResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdResult.Unmarshal(m, b)
}
func (m *CmdResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdResult.Marshal(b, m, deterministic)
}
func (m *CmdResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdResult.Merge(m, src)
}
func (m *CmdResult) XXX_Size() int {
	return xxx_messageInfo_CmdResult.Size(m)
}
func (m *CmdResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdResult.DiscardUnknown(m)
}

var xxx_messageInfo_CmdResult proto.InternalMessageInfo

func (m *CmdResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type FilePath struct {
	Path                 string   `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilePath) Reset()         { *m = FilePath{} }
func (m *FilePath) String() string { return proto.CompactTextString(m) }
func (*FilePath) ProtoMessage()    {}
func (*FilePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_8429525101601a29, []int{1}
}

func (m *FilePath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilePath.Unmarshal(m, b)
}
func (m *FilePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilePath.Marshal(b, m, deterministic)
}
func (m *FilePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilePath.Merge(m, src)
}
func (m *FilePath) XXX_Size() int {
	return xxx_messageInfo_FilePath.Size(m)
}
func (m *FilePath) XXX_DiscardUnknown() {
	xxx_messageInfo_FilePath.DiscardUnknown(m)
}

var xxx_messageInfo_FilePath proto.InternalMessageInfo

func (m *FilePath) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Command struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=Cmd,proto3" json:"Cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_8429525101601a29, []int{2}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

type Dummy struct {
	Dummy                string   `protobuf:"bytes,1,opt,name=Dummy,proto3" json:"Dummy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dummy) Reset()         { *m = Dummy{} }
func (m *Dummy) String() string { return proto.CompactTextString(m) }
func (*Dummy) ProtoMessage()    {}
func (*Dummy) Descriptor() ([]byte, []int) {
	return fileDescriptor_8429525101601a29, []int{3}
}

func (m *Dummy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dummy.Unmarshal(m, b)
}
func (m *Dummy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dummy.Marshal(b, m, deterministic)
}
func (m *Dummy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dummy.Merge(m, src)
}
func (m *Dummy) XXX_Size() int {
	return xxx_messageInfo_Dummy.Size(m)
}
func (m *Dummy) XXX_DiscardUnknown() {
	xxx_messageInfo_Dummy.DiscardUnknown(m)
}

var xxx_messageInfo_Dummy proto.InternalMessageInfo

func (m *Dummy) GetDummy() string {
	if m != nil {
		return m.Dummy
	}
	return ""
}

func init() {
	proto.RegisterType((*CmdResult)(nil), "protos.CmdResult")
	proto.RegisterType((*FilePath)(nil), "protos.FilePath")
	proto.RegisterType((*Command)(nil), "protos.Command")
	proto.RegisterType((*Dummy)(nil), "protos.Dummy")
}

func init() { proto.RegisterFile("remoteExec.proto", fileDescriptor_8429525101601a29) }

var fileDescriptor_8429525101601a29 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x4a, 0xcd, 0xcd,
	0x2f, 0x49, 0x75, 0xad, 0x48, 0x4d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53,
	0xc5, 0x4a, 0xca, 0x5c, 0x9c, 0xce, 0xb9, 0x29, 0x41, 0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x42, 0x62,
	0x5c, 0x6c, 0x10, 0x96, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x94, 0xa7, 0x24, 0xc7, 0xc5,
	0xe1, 0x96, 0x99, 0x93, 0x1a, 0x90, 0x58, 0x92, 0x21, 0x24, 0xc4, 0xc5, 0x02, 0xa2, 0xa1, 0x2a,
	0xc0, 0x6c, 0x25, 0x69, 0x2e, 0x76, 0xe7, 0xfc, 0xdc, 0xdc, 0xc4, 0xbc, 0x14, 0x21, 0x01, 0x2e,
	0x66, 0xe7, 0xdc, 0x14, 0xa8, 0x2c, 0x88, 0xa9, 0x24, 0xcb, 0xc5, 0xea, 0x52, 0x9a, 0x9b, 0x5b,
	0x29, 0x24, 0x02, 0x65, 0x40, 0x25, 0x21, 0x1c, 0xa3, 0x5b, 0x8c, 0x5c, 0x5c, 0x41, 0x70, 0xd7,
	0x09, 0x69, 0x73, 0xb1, 0xba, 0xa7, 0x96, 0x78, 0x06, 0x08, 0xf1, 0x42, 0x1c, 0x5a, 0xac, 0x07,
	0x56, 0x26, 0x25, 0x08, 0xe3, 0xc2, 0x5d, 0xab, 0xc4, 0x20, 0x64, 0xce, 0xc5, 0xe7, 0x9e, 0x5a,
	0x02, 0x72, 0x9a, 0x73, 0x7e, 0x5e, 0x49, 0x6a, 0x5e, 0x89, 0x90, 0x00, 0x4c, 0x19, 0xcc, 0xbd,
	0xd8, 0x35, 0x9a, 0x71, 0xf1, 0x81, 0x6c, 0x2b, 0x2d, 0x49, 0x85, 0xb9, 0x9b, 0x1f, 0xae, 0x0c,
	0x22, 0x80, 0x5d, 0x9f, 0x1e, 0x17, 0x47, 0x40, 0x7e, 0x79, 0x6a, 0x91, 0x7f, 0x5a, 0x1a, 0x31,
	0x0e, 0x4c, 0x82, 0x84, 0xb2, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x30, 0xb4, 0x3b, 0x80,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RemoteExecClient is the client API for RemoteExec service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoteExecClient interface {
	GetIP(ctx context.Context, in *Dummy, opts ...grpc.CallOption) (*CmdResult, error)
	GetFileContent(ctx context.Context, in *FilePath, opts ...grpc.CallOption) (*CmdResult, error)
	ExecuteCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*CmdResult, error)
	PowerOff(ctx context.Context, in *Dummy, opts ...grpc.CallOption) (*CmdResult, error)
}

type remoteExecClient struct {
	cc *grpc.ClientConn
}

func NewRemoteExecClient(cc *grpc.ClientConn) RemoteExecClient {
	return &remoteExecClient{cc}
}

func (c *remoteExecClient) GetIP(ctx context.Context, in *Dummy, opts ...grpc.CallOption) (*CmdResult, error) {
	out := new(CmdResult)
	err := c.cc.Invoke(ctx, "/protos.RemoteExec/GetIP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteExecClient) GetFileContent(ctx context.Context, in *FilePath, opts ...grpc.CallOption) (*CmdResult, error) {
	out := new(CmdResult)
	err := c.cc.Invoke(ctx, "/protos.RemoteExec/GetFileContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteExecClient) ExecuteCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*CmdResult, error) {
	out := new(CmdResult)
	err := c.cc.Invoke(ctx, "/protos.RemoteExec/ExecuteCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteExecClient) PowerOff(ctx context.Context, in *Dummy, opts ...grpc.CallOption) (*CmdResult, error) {
	out := new(CmdResult)
	err := c.cc.Invoke(ctx, "/protos.RemoteExec/PowerOff", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteExecServer is the server API for RemoteExec service.
type RemoteExecServer interface {
	GetIP(context.Context, *Dummy) (*CmdResult, error)
	GetFileContent(context.Context, *FilePath) (*CmdResult, error)
	ExecuteCommand(context.Context, *Command) (*CmdResult, error)
	PowerOff(context.Context, *Dummy) (*CmdResult, error)
}

// UnimplementedRemoteExecServer can be embedded to have forward compatible implementations.
type UnimplementedRemoteExecServer struct {
}

func (*UnimplementedRemoteExecServer) GetIP(ctx context.Context, req *Dummy) (*CmdResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIP not implemented")
}
func (*UnimplementedRemoteExecServer) GetFileContent(ctx context.Context, req *FilePath) (*CmdResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileContent not implemented")
}
func (*UnimplementedRemoteExecServer) ExecuteCommand(ctx context.Context, req *Command) (*CmdResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (*UnimplementedRemoteExecServer) PowerOff(ctx context.Context, req *Dummy) (*CmdResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PowerOff not implemented")
}

func RegisterRemoteExecServer(s *grpc.Server, srv RemoteExecServer) {
	s.RegisterService(&_RemoteExec_serviceDesc, srv)
}

func _RemoteExec_GetIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Dummy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteExecServer).GetIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RemoteExec/GetIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteExecServer).GetIP(ctx, req.(*Dummy))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteExec_GetFileContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilePath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteExecServer).GetFileContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RemoteExec/GetFileContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteExecServer).GetFileContent(ctx, req.(*FilePath))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteExec_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteExecServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RemoteExec/ExecuteCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteExecServer).ExecuteCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteExec_PowerOff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Dummy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteExecServer).PowerOff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RemoteExec/PowerOff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteExecServer).PowerOff(ctx, req.(*Dummy))
	}
	return interceptor(ctx, in, info, handler)
}

var _RemoteExec_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.RemoteExec",
	HandlerType: (*RemoteExecServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIP",
			Handler:    _RemoteExec_GetIP_Handler,
		},
		{
			MethodName: "GetFileContent",
			Handler:    _RemoteExec_GetFileContent_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _RemoteExec_ExecuteCommand_Handler,
		},
		{
			MethodName: "PowerOff",
			Handler:    _RemoteExec_PowerOff_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remoteExec.proto",
}
